use CabTrip;

/** Analysis of Revenue Metrics**/

/** 1. Calculate the total revenue generated by completed bookings in the last 6 months. **/

select date_format(Booking_Time,'%y') as Years,
monthname(Booking_Time) as Month_Name, 
sum(Fare) as Total_Revenue
from Booking_Info
where Status = 'Completed'
and Booking_Time >= Date_sub('2025-09-30 00:00:00', interval 6 month)
and Booking_Time <='2025-09-30 00:00:00'
Group by  Years,Month_Name
Order by Month_Name asc;


/** 2.  Identify the top 3 most frequently traveled routes based on PickupLocation and 
DropoffLocation. **/

/** For All Bookings----No Status applied **/
select concat(Least(Pick_up_Location, Drop_off_Location),
concat(' - ',Greatest(Pick_up_Location, Drop_off_Location))) as Location_Combination,
count(Booking_ID) as Total_Preference
from Booking_Info
Group by  Location_Combination
Order by Total_Preference desc, Location_Combination asc
limit 3;

/** For Status = 'Completed' **/
select concat(Least(Pick_up_Location, Drop_off_Location),
concat(' - ',Greatest(Pick_up_Location, Drop_off_Location))) as Location_Combination,
count(Booking_ID) as Total_Preference
from Booking_Info
where Status = 'Completed'
Group by  Location_Combination
Order by Total_Preference desc, Location_Combination asc
limit 3;

/** 3.  Determine if higher-rated drivers tend to complete more trips and earn higher fares.  **/
Select
    d.Driver_ID,
    d.Driver_Name,
    Count(b.Booking_ID) as Total_Trips, 
    Sum(b.Fare) as Total_Revenew_Earned,
    feedback.Total_Rated
from Driver_Info d
left join Booking_Info b 
on d.Driver_ID = b.Driver_ID and b.Status = 'Completed'
left join (select
    D.Driver_ID,
    D.Driver_Name,
	avg(f.Rating) as Total_Rated
    from Driver_Info D
    left Join Feedback f
    on D.Driver_ID = f.Driver_ID
    Group by D.Driver_ID, D.Driver_Name) as feedback 
on  d.Driver_ID = feedback.Driver_ID
Group by d.Driver_ID, d.Driver_Name
Order by Total_Revenew_Earned desc, feedback.Total_Rated desc;